setcolor("w+/b")
char := chr(177) + chr(176)
retorno := ms_cls()
inkey(0)
setcolor("")
cls
inkey(0)
setcolor("w+/b")
? retorno
? len(retorno)
? ms_replicate("1", 10)
? len(ms_replicate("1", 10))
inkey(0)
setcolor("")
ms_clearscreen()
