@ECHO OFF
COPY LISTALAN.PRG LISTA.PRG
COPY LISTA1LA.PRG LISTA1.PRG
COPY CHELAN.PRG   CHEQUE.PRG
COPY PAGALAN.PRG  PAGAR.PRG
COPY VENLAN.PRG   VEN.PRG
COPY ORCALAN.PRG  ORCA.PRG
COPY RECELAN.PRG  RECE.PRG
COPY PONTOLAN.PRG PONTO.PRG
COPY SCPLAN.PRG   SCP.PRG
COPY SCI.PRG      SCILAN.PRG
COPY SCI.PRG      NEW.PRG
COPY FUNCOES.PRG  FUNC.PRG
COPY FUNCOES.PRG  FUNCNEW.PRG
COPY FUNCOES.PRG  FUNLAN.PRG
COPY TRECEPOSI.PRG RECEPOSI.PRG

copy *.PRG c:\win95_cd\app\sciw
copy *.CH c:\win95_cd\app\sciw
copy *.H c:\win95_cd\app\sciw
copy *.CPP c:\win95_cd\app\sciw
copy *.C c:\win95_cd\app\sciw
copy *.BAT c:\win95_cd\app\sciw
